## Text Summarization

### 1. Bag of Words

In [83]:
import numpy as np
import pandas as pd

df = pd.DataFrame({'text' : ['people watch cricket', 'player was player',
                              'people write comment', 'cricket play comment'],
                   'output' : [1,1,0,0]})

In [84]:
df

,text,output
0,people watch cricket,1
1,player was player,1
2,people write comment,0
3,cricket play comment,0


In [85]:
## Unique words --> people watch cricket player was write comment play
# [11100000]
# [00021000]
# [10000110]
# [00100011]

In [86]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

BOW = cv.fit_transform(df['text'])

# Vocab
print(cv.vocabulary_)

{'people': 2, 'watch': 6, 'cricket': 1, 'player': 4, 'was': 5, 'write': 7, 'comment': 0, 'play': 3}


In [87]:
print(BOW[0].toarray())
print(BOW[1].toarray())

[[0 1 1 0 0 0 1 0]]
[[0 0 0 0 2 1 0 0]]


In [88]:
cv.transform(["cricket watch and write comment of cricket comment"]).toarray()

array([[2, 2, 0, 0, 0, 0, 1, 1]])

### 2. N-Grams

In [89]:
v = CountVectorizer(ngram_range= (1, 2))
bow = v.fit_transform(df['text'])
df['text']

,text
0,people watch cricket
1,player was player
2,people write comment
3,cricket play comment


In [90]:
# vocab
print(v.vocabulary_)

{'people': 3, 'watch': 12, 'cricket': 1, 'people watch': 4, 'watch cricket': 13, 'player': 8, 'was': 10, 'player was': 9, 'was player': 11, 'write': 14, 'comment': 0, 'people write': 5, 'write comment': 15, 'play': 6, 'cricket play': 2, 'play comment': 7}


### 3. TF-IDF (Term Frequency - Inverse Document Frequency)

In [91]:
# TF(t, d) = (number of occurance of term t in document d) / (total number of terms in documnt d)

# Example --> d1 = people watch cricket
# tf(people, d1) = 1 / 3

# d2 = match was match
# tf(match, d2) = 2 / 3

# IDF(t) = log(Total number of documents in corpus / Number of documents with term t in them)
# Here corpus means number of sentences

# Example ==>
# d1 = people watch cricket.
# d2 = cricket was cricket.
# d3 = people write comment.
# d4 = cricket write comment.

# idf(cricket) = log(4/4)
# idf(people) = log(4/2)

In [92]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

tfidf.fit_transform(df['text'])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 11 stored elements and shape (4, 8)>

In [93]:
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.52640543, 0.52640543, 0.        , 0.        ,
        0.        , 0.66767854, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.89442719,
        0.4472136 , 0.        , 0.        ],
       [0.52640543, 0.        , 0.52640543, 0.        , 0.        ,
        0.        , 0.        , 0.66767854],
       [0.52640543, 0.52640543, 0.        , 0.66767854, 0.        ,
        0.        , 0.        , 0.        ]])

In [94]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.51082562 1.51082562 1.51082562 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073]
['comment' 'cricket' 'people' 'play' 'player' 'was' 'watch' 'write']


## Dataset -> IMDB Dataset

In [95]:
df = pd.read_csv('/content/IMDB Dataset - IMDB Dataset.csv')
df.head()

,review,sentiment
0,One of the other reviewers has mentioned that ...,positive
1,A wonderful little production. <br /><br />The...,positive
2,I thought this was a wonderful way to spend ti...,positive
3,Basically there's a family where a little boy ...,negative
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive


In [96]:
## Lowercasing
data = df.loc[0:20].copy()
data['review'] = data['review'].str.lower()

In [97]:
## Removing HTML tags
import re
def remove_html_tags(text):
  pattern = re.compile('<.*?>')
  return pattern.sub(r'', text)

data['review'] = data['review'].apply(remove_html_tags)

In [98]:
## Removing URL's
def remove_url(text):
  pattern = re.compile(r'https?://\S+|www\.\S+')
  return pattern.sub(r'', text)
data['review'] = data['review'].apply(remove_url)

In [99]:
# import string
# string.punctuation

# exclude = string.punctuation

# def remove_punc(text):
#   for char in exclude:
#     text = text.replace(char, '')
#   return text
# data['review'] = data['review'].apply(remove_punc)

In [100]:
# import nltk
# nltk.download('stopwords')
# from nltk.corpus import stopwords

# STOPWORDS = set(stopwords.words('english'))

# def remove_stopwords(text: str):
#   new_text = []
#   for word in text.split():
#     if word in STOPWORDS:
#       new_text.append('')
#     else:
#       new_text.append(word)

#   x = new_text[:]
#   new_text.clear()
#   return "".join(x)

# data['review'] = data['review'].apply(remove_stopwords)

In [101]:
data

,review,sentiment
0,one of the other reviewers has mentioned that ...,positive
1,a wonderful little production. the filming tec...,positive
2,i thought this was a wonderful way to spend ti...,positive
3,basically there's a family where a little boy ...,negative
4,"petter mattei's ""love in the time of money"" is...",positive
5,"probably my all-time favorite movie, a story o...",positive
6,i sure would like to see a resurrection of a u...,positive
7,"this show was an amazing, fresh & innovative i...",negative
8,encouraged by the positive comments about this...,negative
9,if you like original gut wrenching laughter yo...,positive


In [102]:
import nltk
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
nltk.download('omw-1.4')

lemmatizer = WordNetLemmatizer()

data['review'] = data['review'].apply(lambda x: lemmatizer.lemmatize(x))

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [103]:
data

,review,sentiment
0,one of the other reviewers has mentioned that ...,positive
1,a wonderful little production. the filming tec...,positive
2,i thought this was a wonderful way to spend ti...,positive
3,basically there's a family where a little boy ...,negative
4,"petter mattei's ""love in the time of money"" is...",positive
5,"probably my all-time favorite movie, a story o...",positive
6,i sure would like to see a resurrection of a u...,positive
7,"this show was an amazing, fresh & innovative i...",negative
8,encouraged by the positive comments about this...,negative
9,if you like original gut wrenching laughter yo...,positive


In [104]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

tfidf.fit_transform(data['review']).toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.04366977,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.0748971 , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.09353528,
        0.        ]])

In [105]:
print(tfidf.idf_)
print(tfidf.vocabulary_)

[2.70474809 3.39789527 3.39789527 ... 2.70474809 2.70474809 3.39789527]
{'one': 736, 'of': 727, 'the': 1066, 'other': 744, 'reviewers': 871, 'has': 472, 'mentioned': 665, 'that': 1064, 'after': 29, 'watching': 1173, 'just': 559, 'oz': 753, 'episode': 323, 'you': 1228, 'll': 610, 'be': 96, 'hooked': 495, 'they': 1074, 'are': 66, 'right': 876, 'as': 74, 'this': 1080, 'is': 541, 'exactly': 336, 'what': 1184, 'happened': 465, 'with': 1199, 'me': 657, 'first': 386, 'thing': 1075, 'struck': 1023, 'about': 12, 'was': 1166, 'its': 545, 'brutality': 141, 'and': 53, 'unflinching': 1132, 'scenes': 907, 'violence': 1153, 'which': 1187, 'set': 938, 'in': 523, 'from': 406, 'word': 1207, 'go': 431, 'trust': 1116, 'not': 718, 'show': 953, 'for': 394, 'faint': 359, 'hearted': 478, 'or': 739, 'timid': 1094, 'pulls': 827, 'no': 714, 'punches': 828, 'regards': 853, 'to': 1097, 'drugs': 293, 'sex': 940, 'hardcore': 470, 'classic': 183, 'use': 1138, 'it': 543, 'called': 150, 'nickname': 712, 'given': 424, '